name: "VS Marketplace Publisher"
description: "Publish VisualStudio extension to the Marketplace"
inputs:
  token: # id of input
    description: "Token to access you repository"
    required: true
outputs:
  asset_file:
    description: "File path to downloaded asset"
runs:
  using: "node12"
  main: "../dist/index.js"
