# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vssdk\VisualStudioIntegration\tools\bin\*.exe"

      - name: Run a one-line script
        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vssdk\VisualStudioIntegration\tools\bin\VsixPublisher.exe"

      - name: Download latest assets
        id: download_asset
        uses: ./ #mrluje/vs-marketplace-publisher@v2
        with:
          # github_token: ${{ secrets.github_token }}
          pat: ${{ secrets.vs_pat }}
          manifestPath: vsixManifest.json
          useLatestReleaseAsset: true
      # Use the output from the `hello` step
      - name: Check downloaded file
        run: |
          dir ${{ steps.download_asset.outputs.asset_file }}
